import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./src/Redux/lib/Providers";
import { store } from "./src/Redux/store";






const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
      </head>
      <Providers store={store}>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
